version: '3'
services:
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/config/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: Asia/Tokyo

  php:
    image: php:7.4-fpm
    volumes:
      - ./www:/usr/share/nginx/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on: 
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www:/usr/share/nginx/html
    ports:
      - 8080:80
    depends_on:
      - php